#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

mkdir yocto

cd yocto

git clone -b dunfell git://git.yoctoproject.org/poky
git clone -b dunfell https://github.com/openembedded/meta-openembedded.git
git clone -b dunfell https://github.com/mendersoftware/meta-mender.git
cp -r ${script_dir}/mender-python-client .

source poky/oe-init-build-env

cp ${script_dir}/{bblayers,local}.conf ./conf

export LANG=en_US.UTF-8
# bitbake core-image-full-cmdline
