#! /bin/bash

# Run the original mender updater as a sub-updater to the mender-python-client
#
# This script is run by the API client through the symlink to /usr/share/mender/install

set -x

MENDER_PYTHON_CLIENT_LOCKFILE=/var/lib/mender/update.lock

msg () {
  echo >&2 "$@"
  echo "$@" >> /var/lib/mender/sub-updater.log
}

program_present () {
  which "$1" || { echo "$1 not found in PATH"; exit 1; }
}

program_present "mender"
program_present "mender-python-client"

if [[ $# -eq 1 ]]; then
  ARTIFACT_PATH="$1"
  mender install "${ARTIFACT_PATH}" || { ret=$?;\
                                               msg "Failed to install the update...";\
                                               mender-python-client report --failure && rm ${MENDER_PYTHON_CLIENT_LOCKFILE}
                                               exit ${ret}; }
  reboot
  exit 0
else
  mender commit
  ret=$?
  case ${ret} in
    0)
      msg "Update successful. Restarting the Mender-Python API client..."
      if mender-python-client report --success
      then
        rm ${MENDER_PYTHON_CLIENT_LOCKFILE}
        exit 0
      else
        exit 1
      fi
      ;;
    2)
      msg "No update is currently in progress..."
      if [ -e /var/lib/mender/update.lock ]; then
        msg "An update was seemingly in progress, and failed"
        if ! mender-python-client report --failure
        then
          msg "An update failed to apply. And the client failed to report the update. Exit code: $?"
        else
          msg "Reported a failed update to the server"
          msg "Removing the lockfile"
          rm ${MENDER_PYTHON_CLIENT_LOCKFILE}
        fi
      fi
      exit 0
      ;;
    *)
      msg "Unexpected 'mender commit' error code ${ret}"
      exit 1
      ;;
  esac
fi
